name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        env:
          VITE_BASE_PATH: /three-lightmap-baker/
        run: pnpm run build

      - name: Create .nojekyll
        run: touch dist/.nojekyll

      - name: Debug build output
        run: ls -R dist

      - name: Publish production site
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          keep_files: true
          full_commit_message: Deploy production site from ${{ github.sha }}
